"use client";

import Link from "next/link";
import { SectionHeading } from "./Pricing";

// Marketing showcase block for the AI social-media automation offering.
// Presents the "posts itself every day" service, matching the site's neon style.

const BENEFITS = [
  "A fresh, on-brand post generated by AI — every single day",
  "Your logo, colours and voice applied automatically",
  "Published hands-free at the best time to post",
  "You approve before anything goes live — full control",
  "Locked to your brand rules, so nothing off-brand slips out",
];

const STEPS = [
  { n: "1", title: "AI writes & designs", desc: "A new branded post is created each day from your rules." },
  { n: "2", title: "You approve", desc: "Give it a glance and a thumbs-up — or let it run on autopilot." },
  { n: "3", title: "It publishes itself", desc: "Scheduled and posted for you, every day, automatically." },
];

// Rotating sample "auto-generated" posts (code-rendered, no images).
const SAMPLES = [
  { tag: "Today", accent: "#22E3C4", title: "Clear terms,", title2: "fewer late payments.", eyebrow: "Credit control" },
  { tag: "Tomorrow", accent: "#FF45C8", title: "Getting", title2: "you paid.", eyebrow: "How it works" },
  { tag: "Wed", accent: "#9B5CFF", title: "Firm, fair,", title2: "friendly.", eyebrow: "Our approach" },
];

export default function SocialAutomation() {
  return (
    <section id="automation" className="relative overflow-hidden border-y border-white/5 bg-ink-900/40">
      <div aria-hidden="true" className="pointer-events-none absolute inset-0">
        <div className="absolute -right-10 top-0 h-56 w-56 rounded-full bg-neon-cyan/15 blur-3xl" />
        <div className="absolute bottom-0 left-0 h-64 w-64 rounded-full bg-neon-green/10 blur-3xl" />
      </div>

      <div className="relative mx-auto max-w-6xl px-4 py-16 sm:py-24">
        <SectionHeading
          eyebrow="AI Automation"
          title={<>Social media that <span className="neon-text">posts itself</span></>}
          sub="Beyond done-for-you — a fully automated system that creates and publishes an on-brand post every day, with zero effort from you."
        />

        <div className="mt-12 grid items-center gap-10 lg:grid-cols-2">
          {/* Copy */}
          <div>
            <span className="inline-flex items-center gap-2 rounded-full border border-neon-cyan/40 bg-neon-cyan/[0.08] px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-neon-cyan">
              <span className="h-2 w-2 rounded-full bg-neon-cyan shadow-glow-cyan" />
              Fully automated
            </span>

            <h3 className="mt-4 font-display text-2xl font-bold leading-tight tracking-tight text-white sm:text-3xl">
              Set it once. It runs every day.
            </h3>
            <p className="mt-3 max-w-xl text-lg leading-relaxed text-slate-300">
              We build the automation around your brand, then it takes over — writing the caption,
              designing the graphic and scheduling the post, day after day, so your feed never goes quiet.
            </p>

            <ul className="mt-6 space-y-3">
              {BENEFITS.map((b) => (
                <li key={b} className="flex items-start gap-2.5 text-slate-200">
                  <svg viewBox="0 0 24 24" fill="none" className="mt-0.5 h-5 w-5 flex-shrink-0 text-neon-green" aria-hidden="true">
                    <path d="M5 13l4 4L19 7" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                  {b}
                </li>
              ))}
            </ul>

            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <Link href="/#quote" className="btn-neon">
                Automate my socials
              </Link>
              <Link href="/social-media" className="btn-ghost">
                See social media plans
              </Link>
            </div>
          </div>

          {/* Visual: an automated "today's post" panel */}
          <div className="relative mx-auto w-full max-w-sm">
            <div className="rounded-[2rem] border border-white/10 bg-ink-900 p-4 shadow-2xl shadow-black/50">
              <div className="mb-3 flex items-center justify-between px-1">
                <div className="flex items-center gap-2">
                  <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-r from-neon-cyan to-neon-green text-ink-950">
                    <svg viewBox="0 0 24 24" fill="none" className="h-4 w-4" aria-hidden="true">
                      <path d="M13 2 4 14h7l-1 8 9-12h-7l1-8Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </span>
                  <span className="text-sm font-bold text-white">Auto-generated</span>
                </div>
                <span className="inline-flex items-center gap-1 rounded-full border border-neon-green/40 bg-neon-green/[0.08] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-neon-green">
                  <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-neon-green" /> Posts 9:00am
                </span>
              </div>

              {/* The lead "today" post */}
              <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold uppercase tracking-widest" style={{ color: SAMPLES[0].accent }}>
                    {SAMPLES[0].eyebrow}
                  </span>
                  <span className="rounded-full px-2 py-0.5 text-[10px] font-bold" style={{ color: SAMPLES[0].accent, background: `${SAMPLES[0].accent}1a` }}>
                    {SAMPLES[0].tag}
                  </span>
                </div>
                <div
                  className="mt-2.5 flex h-28 flex-col justify-center rounded-xl px-3"
                  style={{ background: `linear-gradient(135deg, ${SAMPLES[0].accent}26, transparent)` }}
                >
                  <p className="font-display text-lg font-bold leading-tight text-white">{SAMPLES[0].title}</p>
                  <p className="font-display text-lg font-bold leading-tight text-white/80">{SAMPLES[0].title2}</p>
                </div>
                <div className="mt-2.5 space-y-1.5">
                  <div className="h-1.5 w-full rounded bg-white/10" />
                  <div className="h-1.5 w-4/5 rounded bg-white/10" />
                </div>
                <div className="mt-2.5 flex items-center gap-2 text-[10px] font-medium text-neon-green">
                  <svg viewBox="0 0 24 24" fill="none" className="h-3.5 w-3.5" aria-hidden="true">
                    <path d="M5 13l4 4L19 7" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                  Brand-checked · Scheduled · Published
                </div>
              </div>

              {/* Upcoming days queued */}
              <div className="mt-3 grid grid-cols-2 gap-2">
                {SAMPLES.slice(1).map((s) => (
                  <div key={s.tag} className="rounded-xl border border-white/10 bg-white/[0.03] p-2.5">
                    <div className="flex items-center justify-between">
                      <span className="text-[9px] font-bold uppercase tracking-wider text-slate-400">{s.tag}</span>
                      <span className="h-1.5 w-1.5 rounded-full" style={{ background: s.accent }} />
                    </div>
                    <div className="mt-1.5 h-10 rounded-lg" style={{ background: `linear-gradient(135deg, ${s.accent}26, transparent)` }} />
                    <p className="mt-1.5 text-[10px] font-semibold leading-tight text-slate-300">{s.title} {s.title2}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* How it works — 3 steps */}
        <div className="mt-14 grid gap-4 sm:grid-cols-3">
          {STEPS.map((s) => (
            <div key={s.n} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
              <span className="flex h-10 w-10 items-center justify-center rounded-xl border border-neon-cyan/30 bg-neon-cyan/10 font-display text-lg font-bold text-neon-cyan">
                {s.n}
              </span>
              <h4 className="mt-3 font-semibold text-white">{s.title}</h4>
              <p className="mt-1 text-sm text-slate-400">{s.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
